"""s7

Revision ID: 442fb716bfc1
Revises: 351d613f09d8
Create Date: 2020-12-21 10:07:03.195423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442fb716bfc1'
down_revision = '351d613f09d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    code = op.create_table('s7_code',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(code,
                   [
                       {'id': 1,'description': '0IK'},
                       {'id': 2, 'description': '0CC'},
                       {'id': 3, 'description': '0CD'},
                       {'id': 4, 'description': '0DD'}
                   ])

    flight = op.create_table('s7_flight',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('air_uuid', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('air_uuid')
    )
    op.bulk_insert(flight,
                   [
                       {'id': 1,'air_uuid': 'ef8ff876-9b29-448f-97ba-094898deef98'},
                       {'id': 2, 'air_uuid': 'ef8ff876-9b29-448f-97ba-32423e31df34'}
                   ])

    passanger = op.create_table('s7_passanger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('passport', sa.String(length=64), nullable=True),
    sa.Column('order', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(passanger,
                   [
                       {'id': 1,'name': 'Ivan', 'last_name': 'Ivanov', 'passport': 'dKCLeweYNb6iDO66', 'order': '345345ae6345'},
                       {'id': 2, 'name': 'Petr', 'last_name': 'Petrov', 'passport': 'qauJTpuMlDrASaty', 'order': '689682348682'}
                   ])

    baggage = op.create_table('s7_baggage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('overweight', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('weight', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.Column('code', sa.BigInteger(), nullable=False),
    sa.Column('passanger_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['s7_code.id'], ),
    sa.ForeignKeyConstraint(['passanger_id'], ['s7_passanger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(baggage,
                   [
                       {'id': 1,
                        'overweight': True,
                        'amount': 1,
                        'unit': 'KG',
                        'weight': 50,
                        'code': 1,
                        'description': 'EXCESS WEIGHT',
                        'registered': False,
                        'passanger_id': 1
                        },
                       {'id': 2,
                        'overweight': False,
                        'amount': 1,
                        'unit': 'PC',
                        'weight': 23,
                        'code': 2,
                        'description': 'CHECKED BAG FIRST',
                        'registered': False,
                        'passanger_id': 1
                        },
                       {'id': 3,
                        'overweight': False,
                        'amount': 2,
                        'unit': 'PC',
                        'weight': 23,
                        'code': 3,
                        'description': 'CHECKED BAG SECOND',
                        'registered': False,
                        'passanger_id': 1
                        },
                       {'id': 4,
                        'overweight': False,
                        'amount': 1,
                        'unit': 'PC',
                        'weight': 1,
                        'code': 4,
                        'description': 'SNOW SKI SNOWBOARD EQUIPMENT',
                        'registered': False,
                        'passanger_id': 2
                        }
                   ])

    flight_baggage = op.create_table('flight_baggage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.BigInteger(), nullable=False),
    sa.Column('baggage_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['baggage_id'], ['s7_baggage.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['s7_flight.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(flight_baggage,
                   [
                       {'id': 1,'flight_id': 1, 'baggage_id': 1},
                       {'id': 2,'flight_id': 1, 'baggage_id': 2},
                       {'id': 3, 'flight_id': 1, 'baggage_id': 3},
                       {'id': 4, 'flight_id': 2, 'baggage_id': 4},
                   ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_baggage')
    op.drop_table('s7_baggage')
    op.drop_table('s7_passanger')
    op.drop_table('s7_flight')
    op.drop_table('s7_code')
    # ### end Alembic commands ###
