"""users table

Revision ID: e32dd245038a
Revises: 
Create Date: 2020-09-28 19:49:07.183200

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash

# revision identifiers, used by Alembic.
revision = 'e32dd245038a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userr = op.create_table('userr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userr_email'), 'userr', ['email'], unique=True)
    op.create_index(op.f('ix_userr_username'), 'userr', ['username'], unique=True)
    # ### end Alembic commands ###

    op.bulk_insert(userr,
                   [
                       {
                           'id': 1,
                           'username': 'guest',
                           'email': 'almaz_1c@mail.ru',
                           'password_hash': generate_password_hash('guest1')
                       }
                   ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userr_username'), table_name='userr')
    op.drop_index(op.f('ix_userr_email'), table_name='userr')
    op.drop_table('userr')
    # ### end Alembic commands ###
